version: '3.8'

services:
  # NestJS Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todolist-nestjs-app
    # ports:
    #   - "3000:3000"
    network_mode: "host"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://root:root@localhost:3309/todo_list_app
      - PORT=3000
    # depends_on:
    #   db:
    #     condition: service_healthy
    volumes:
      - ./uploads:/app/uploads
    # networks:
    #   - todolist-network
    restart: unless-stopped

  # MySQL Database
  # db:
  #   image: mysql:8.0
  #   container_name: todolist-mysql-db
  #   environment:
  #     MYSQL_ROOT_PASSWORD: rootpassword
  #     MYSQL_DATABASE: todolist_nestjs
  #     MYSQL_USER: todouser
  #     MYSQL_PASSWORD: todopass
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #     - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
  #   networks:
  #     - todolist-network
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
  #     timeout: 20s
  #     retries: 10
  #     interval: 10s
  #     start_period: 40s

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    container_name: todolist-redis-nestjs
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - todolist-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 3s
      retries: 5
      interval: 10s

  # PhpMyAdmin for database management
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: todolist-phpmyadmin
  #   environment:
  #     PMA_HOST: db
  #     PMA_PORT: 3306
  #     PMA_USER: todouser
  #     PMA_PASSWORD: todopass
  #     MYSQL_ROOT_PASSWORD: rootpassword
  #   ports:
  #     - "8080:80"
  #   # depends_on:
  #   #   - db
  #   networks:
  #     - todolist-network
  #   restart: unless-stopped

volumes:
  # mysql_data:
  #   driver: local
  redis_data:
    driver: local

networks:
  todolist-network:
    driver: bridge